# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlataform: 'Any CPU'
  SolutionPath: 'Caritas.ServiceAPI/Caritas.ServiceAPI.sln'
  buildConfiguration: 'Release'

steps:
  
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    
- task: FtpUpload@2
  displayName: 'FTP Upload'
  inputs:
    credentialsOption: inputs
    serverUrl: 'ftp://cadubt.com.br'
    username: cadubt
    password: 00caduzice
    rootDirectory: '$(Build.SourcesDirectory)'
    remoteDirectory: '/www/api-caritas/'
    trustSSL: true